<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

|Term|Brief description|
|-|-|
|Subsetting|*To select something from an iterable*|
|Indexing|*To select one thing from an iterable*|
|Slicing|*To select more than one things from an iterable using a range*|
|Masking|*To select more than one things from an iterable by specifying a condition*|

In [ ]:
import numpy as np                  # No need to import pandas, numpy already has method astype()

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbersStr = np_array_2d[0:10, 0]   # Fetches elements from 0 to 9, then take the 0th sub-element of each element.
numbersInt = numbersStr.astype(int)
binaryMask = numbersInt % 2         # Converts to modulo 2   
booleanMask = binaryMask == 1       # Condition that number is odd

result = np_array_2d[booleanMask, 1]    # booleanMask filters out the [int, char] elements, while 1 leaves only the char elements
print(result)

['A' 'C' 'E' 'G' 'I']


In [27]:
npArr2d = np.array([[66, 50, 57, -1, -1],
                    [92, -1, 88, -1, -1],
                    [75, -1, -1, 76, -1],
                    [-1, 51, 87, -1, -1],
                    [71, -1, 67, -1, 69]])

under50Mask = npArr2d < 50
over50Mask = npArr2d > 50
fiftyMask = npArr2d == 50

for i in range(len(npArr2d)):
    for j in range(len(npArr2d[i])):
        if under50Mask[i, j]:
            npArr2d[i, j] = -1
        elif over50Mask[i, j]:
            npArr2d[i, j] = 1
        elif fiftyMask[i, j]:
            npArr2d[i, j] = 0
        else:
            print('Something went wrong.')
            break 

print(npArr2d)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
